# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "19d9e420c7823afc3b6f2f252347ae1d"
name = "discount-countown-app"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[app_proxy]
url = "https://abcd-12345679371.myshopify.com/proxy/widget"
subpath = "timer-widget"
prefix = "apps"
